# Generated by Django 4.2.7 on 2024-02-17 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_address_communitymember_communitymemberendorsement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(choices=[('L', 'Low Risk'), ('M', 'Medium Risk'), ('H', 'High Risk'), ('E', 'Emergency')], default='E', max_length=1)),
                ('law_enforcement_involve', models.BooleanField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.communitymember')),
            ],
        ),
    ]
